name: Echo good morning

on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      - develop       # run automatically on pushes to develop
      # - master      # optionally, add other branches

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run: echo "morning"
